services:
  db:
    container_name: booster_container
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: booster_db
    ports:
      - '5432:5432'
  pgadmin:
    container_name: pgadming4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: adming@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
